apiVersion: v1
kind: Pod
metadata:
  name: project-stack
  labels:
    app: project-stack
spec:
  containers:
  - name: project-stack
    image: modularniurad/project-stack
    imagePullPolicy: Never
    env:
    - name: DATABASE_URL
      value: postgres://gandalf:hovno@postgre-service/gis
    - name: HOST
      value: 0.0.0.0
